services:
  - type: web
    name: greentrace-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python simple_server.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://greentrace-frontend.vercel.app,https://greentrace-app.vercel.app"
      - key: STATIC_URL
        value: "/static/"
      - key: MEDIA_URL
        value: "/media/"