# Generated by Django 5.2.5 on 2025-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('batch_id', models.CharField(help_text='Unique batch identifier', max_length=100, unique=True)),
                ('certification', models.CharField(choices=[('organic', 'Organic'), ('fair-trade', 'Fair Trade'), ('rainforest-alliance', 'Rainforest Alliance'), ('carbon-neutral', 'Carbon Neutral'), ('sustainable', 'Sustainable'), ('regenerative-organic', 'Regenerative Organic'), ('none', 'None')], default='none', help_text='Product certification type', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Production location', max_length=500)),
                ('producer', models.CharField(blank=True, help_text='Producer name or organization', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('carbon_activity', models.TextField(blank=True, help_text='Carbon reduction activities and sustainable practices')),
                ('iot_data', models.TextField(blank=True, help_text='IoT sensor data (temperature, humidity, soil data, etc.)')),
                ('is_sensitive_data_public', models.BooleanField(default=False, help_text='Whether sensitive data is publicly visible')),
                ('is_producer_details_public', models.BooleanField(default=False, help_text='Whether producer details are publicly visible')),
                ('is_iot_data_public', models.BooleanField(default=False, help_text='Whether IoT data is publicly visible')),
                ('is_carbon_details_public', models.BooleanField(default=False, help_text='Whether carbon details are publicly visible')),
                ('blockchain_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('blockchain_network', models.CharField(default='avalanche-fuji', help_text='Blockchain network used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('view', 'View'), ('delete', 'Delete'), ('data_access', 'Data Access')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Audit Log',
                'verbose_name_plural': 'Product Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
