# Generated by Django 5.2.5 on 2025-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('model_name', models.CharField(help_text='Model being accessed', max_length=100)),
                ('object_id', models.CharField(help_text='Object ID accessed', max_length=100)),
                ('field_names', models.JSONField(default=list, help_text='Fields accessed')),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('enterprise', 'Enterprise')], max_length=20)),
                ('data_sensitivity', models.CharField(help_text='Data sensitivity level', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Access Log',
                'verbose_name_plural': 'Data Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('enterprise', 'Enterprise')], default='public', help_text='Privacy level', max_length=20)),
                ('show_sensitive_data', models.BooleanField(default=True, help_text='Show sensitive product data')),
                ('show_producer_details', models.BooleanField(default=True, help_text='Show producer details')),
                ('show_iot_data', models.BooleanField(default=True, help_text='Show IoT sensor data')),
                ('show_carbon_details', models.BooleanField(default=True, help_text='Show carbon activity details')),
                ('show_certification_details', models.BooleanField(default=True, help_text='Show certification details')),
                ('eerc_compliant', models.BooleanField(default=False, help_text='eERC compliance enabled')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Data retention period in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
            },
        ),
    ]
