# Generated by Django 5.2.5 on 2025-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCredit',
            fields=[
                ('id', models.CharField(help_text='Unique credit identifier', max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount', max_digits=10)),
                ('unit', models.CharField(default='tonnes', help_text='Credit unit (tonnes, kg, etc.)', max_length=20)),
                ('issuer', models.CharField(help_text='Credit issuer', max_length=200)),
                ('recipient', models.CharField(help_text='Credit recipient', max_length=200)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('transferred', 'Transferred'), ('retired', 'Retired')], default='issued', help_text='Current credit status', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status', max_length=20)),
                ('description', models.TextField(help_text='Credit description and methodology')),
                ('carbon_offset', models.TextField(help_text='Carbon offset activities and verification')),
                ('blockchain_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('blockchain_network', models.CharField(default='avalanche-fuji', help_text='Blockchain network used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for retirement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Credit',
                'verbose_name_plural': 'Carbon Credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
