# Generated by Django 5.2.5 on 2025-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('public', 'Public User'), ('private', 'Private User'), ('enterprise', 'Enterprise Partner'), ('admin', 'Administrator/Regulator')], default='public', help_text='User access level', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Organization name', max_length=200)),
                ('position', models.CharField(blank=True, help_text='Job position', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Address')),
                ('privacy_level', models.CharField(choices=[('public', 'Public User'), ('private', 'Private User'), ('enterprise', 'Enterprise Partner'), ('admin', 'Administrator/Regulator')], default='public', help_text='Default privacy level', max_length=20)),
                ('wallet_address', models.CharField(blank=True, help_text='Blockchain wallet address', max_length=42)),
                ('blockchain_network', models.CharField(default='avalanche-fuji', help_text='Preferred blockchain network', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
